# https://dart.dev/guides/language/analysis-options
# https://github.com/dart-lang/language/tree/master/resources/type-system

include: package:very_good_analysis/analysis_options.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    always_put_required_named_parameters_first: true
    always_use_package_imports: false
    avoid_annotating_with_dynamic: true
    avoid_types_on_closure_parameters: true
    lines_longer_than_80_chars: false
    public_member_api_docs: true
    sort_constructors_first: false
